# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Plan

# Model Form Field configuration
form: $/responsiv/subscribe/models/plan/fields.yaml

# Model Class name
modelClass: Responsiv\Subscribe\Models\Plan

# Default redirect location
defaultRedirect: responsiv/subscribe/plans

# Create page
create:
    title: Create Plan
    redirect: responsiv/subscribe/plans/update/:id
    redirectClose: responsiv/subscribe/plans

# Update page
update:
    title: Edit Plan
    redirect: responsiv/subscribe/plans
    redirectClose: responsiv/subscribe/plans

# Preview page
preview:
    title: Preview Plan