# ===================================
#  Relation Behavior Config
# ===================================

invoices:
    label: Invoice
    readOnly: true
    view:
        list: $/responsiv/subscribe/models/membership/invoice_columns.yaml
        recordUrl: responsiv/pay/invoices/preview/:id
        toolbarButtons: null
